In [1]:
import pandas as pd
from sqlalchemy import create_engine

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Renukadevi$786@localhost:5432/Chinook_SQL_Project"
)

print("Database connection object created!")

Database connection object created!

In [3]:
with engine.connect() as connection:
    print("Connected to PostgreSQL successfully!")

Connected to PostgreSQL successfully!

In [4]:
query = """
SELECT *
FROM customer
LIMIT 10;
"""

df = pd.read_sql_query(query, engine)

df

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5
6,7,Astrid,Gruber,NaN,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,NaN,Austria,1010,+43 01 5134505,NaN,astrid.gruber@apple.at,5
7,8,Daan,Peeters,NaN,Grétrystraat 63,Brussels,NaN,Belgium,1000,+32 02 219 03 03,NaN,daan_peeters@apple.be,4
8,9,Kara,Nielsen,NaN,Sønder Boulevard 51,Copenhagen,NaN,Denmark,1720,+453 3331 9991,NaN,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4

### Q1 - Explore the database tables
##### Business question - What tables are available in the Chinook database?

In [5]:
# Q1 — What tables are available in the database?

query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
"""

df = pd.read_sql_query(query, engine)
df

        table_name
0            album
1           artist
2         customer
3         employee
4            genre
5          invoice
6     invoice_line
7       media_type
8         playlist
9   playlist_track
10           track

### Q2 - Display the first 10 customers
##### Business question - Who are the customers in the store?

In [6]:
# Q2 — Display the first 10 customers

query = """
SELECT
    customer_id,
    first_name,
    last_name,
    email,
    city,
    country
FROM customer
LIMIT 10;
"""

df = pd.read_sql_query(query, engine)
df

,customer_id,first_name,last_name,email,city,country
0,1,Luís,Gonçalves,luisg@embraer.com.br,São José dos Campos,Brazil
1,2,Leonie,Köhler,leonekohler@surfeu.de,Stuttgart,Germany
2,3,François,Tremblay,ftremblay@gmail.com,Montréal,Canada
3,4,Bjørn,Hansen,bjorn.hansen@yahoo.no,Oslo,Norway
4,5,František,Wichterlová,frantisekw@jetbrains.com,Prague,Czech Republic
5,6,Helena,Holý,hholy@gmail.com,Prague,Czech Republic
6,7,Astrid,Gruber,astrid.gruber@apple.at,Vienne,Austria
7,8,Daan,Peeters,daan_peeters@apple.be,Brussels,Belgium
8,9,Kara,Nielsen,kara.nielsen@jubii.dk,Copenhagen,Denmark
9,10,Eduardo,Martins,eduardo@woodstock.com.br,São Paulo,Brazil

### Q3 - Find customers from the USA
##### Business question - Which customers are located in the USA?

In [7]:
# Q3 — Which customers are from the USA?

query = """
SELECT
    customer_id,
    first_name,
    last_name,
    city,
    state,
    country
FROM customer
WHERE country = 'USA'
ORDER BY last_name, first_name;
"""

df = pd.read_sql_query(query, engine)
df

    customer_id first_name   last_name            city state country
0            28      Julia     Barnett  Salt Lake City    UT     USA
1            18   Michelle      Brooks        New York    NY     USA
2            21      Kathy       Chase            Reno    NV     USA
3            26    Richard  Cunningham      Fort Worth    TX     USA
4            23       John      Gordon          Boston    MA     USA
5            19        Tim       Goyer       Cupertino    CA     USA
6            27    Patrick        Gray          Tucson    AZ     USA
7            16      Frank      Harris   Mountain View    CA     USA
8            22    Heather     Leacock         Orlando    FL     USA
9            20        Dan      Miller   Mountain View    CA     USA
10           24      Frank     Ralston         Chicago    IL     USA
11           17       Jack       Smith         Redmond    WA     USA
12           25     Victor     Stevens         Madison    WI     USA

### Q4 - Filter customers using logical conditions
##### Business question - Which customers are from the USA and have a phone number recorded?

In [8]:
# Q4 — USA customers with a phone number

query = """
SELECT
    customer_id,
    first_name,
    last_name,
    phone,
    country
FROM customer
WHERE country = 'USA'
  AND phone IS NOT NULL
ORDER BY last_name, first_name;
"""

df = pd.read_sql_query(query, engine)
df

    customer_id first_name   last_name              phone country
0            28      Julia     Barnett  +1 (801) 531-7272     USA
1            18   Michelle      Brooks  +1 (212) 221-3546     USA
2            21      Kathy       Chase  +1 (775) 223-7665     USA
3            26    Richard  Cunningham  +1 (817) 924-7272     USA
4            23       John      Gordon  +1 (617) 522-1333     USA
5            19        Tim       Goyer  +1 (408) 996-1010     USA
6            27    Patrick        Gray  +1 (520) 622-4200     USA
7            16      Frank      Harris  +1 (650) 253-0000     USA
8            22    Heather     Leacock  +1 (407) 999-7788     USA
9            20        Dan      Miller  +1 (650) 644-3358     USA
10           24      Frank     Ralston  +1 (312) 332-3232     USA
11           17       Jack       Smith  +1 (425) 882-8080     USA
12           25     Victor     Stevens  +1 (608) 257-0597     USA

### Q5 - Use multiple country filters
##### Business question: Which customers are from the USA, Canada, or Brazil?

In [9]:
# Q5 — Customers from selected countries

query = """
SELECT
    customer_id,
    first_name,
    last_name,
    country
FROM customer
WHERE country IN ('USA', 'Canada', 'Brazil')
ORDER BY country, last_name, first_name;
"""

df = pd.read_sql_query(query, engine)
df

    customer_id first_name   last_name country
0            12    Roberto     Almeida  Brazil
1             1       Luís   Gonçalves  Brazil
2            10    Eduardo     Martins  Brazil
3            13   Fernanda       Ramos  Brazil
4            11  Alexandre       Rocha  Brazil
5            29     Robert       Brown  Canada
6            30     Edward     Francis  Canada
7            32      Aaron    Mitchell  Canada
8            15   Jennifer    Peterson  Canada
9            14       Mark     Philips  Canada
10           31     Martha        Silk  Canada
11           33      Ellie    Sullivan  Canada
12            3   François    Tremblay  Canada
13           28      Julia     Barnett     USA
14           18   Michelle      Brooks     USA
15           21      Kathy       Chase     USA
16           26    Richard  Cunningham     USA
17           23       John      Gordon     USA
18           19        Tim       Goyer     USA
19           27    Patrick        Gray     USA
20           16      Frank      Harris     USA
21           22    Heather     Leacock     USA
22           20        Dan      Miller     USA
23           24      Frank     Ralston     USA
24           17       Jack       Smith     USA
25           25     Victor     Stevens     USA

IN is a convenient way of expressing multiple OR conditions.

### Q6 - Find tracks above a given price
##### Business question - Which tracks cost more than $1?

In [10]:
# Q6 - Tracks costing more than $1

query = """
SELECT
    track_id,
    name AS track_name,
    unit_price
FROM track
WHERE unit_price > 1.00
ORDER BY unit_price DESC;
"""

df = pd.read_sql_query(query, engine)
df

     track_id                              track_name  unit_price
0        2819  Battlestar Galactica: The Story So Far        1.99
1        2820                  Occupation / Precipice        1.99
2        2821                           Exodus, Pt. 1        1.99
3        2822                           Exodus, Pt. 2        1.99
4        2823                           Collaborators        1.99
..        ...                                     ...         ...
208      3362       There's No Place Like Home, Pt. 1        1.99
209      3363       There's No Place Like Home, Pt. 2        1.99
210      3364       There's No Place Like Home, Pt. 3        1.99
211      3428                          Branch Closing        1.99
212      3429                              The Return        1.99

[213 rows x 3 columns]

### Q7 - Find the most expensive tracks
##### Business question - What are the 10 most expensive tracks?

In [11]:
# Q7 - Top 10 most expensive tracks

query = """
SELECT
    track_id,
    name AS track_name,
    unit_price
FROM track
ORDER BY unit_price DESC
LIMIT 10;
"""

df = pd.read_sql_query(query, engine)
df

   track_id                              track_name  unit_price
0      2824                                    Torn        1.99
1      2827                     Unfinished Business        1.99
2      2821                           Exodus, Pt. 1        1.99
3      2823                           Collaborators        1.99
4      2825                  A Measure of Salvation        1.99
5      2826                                    Hero        1.99
6      2819  Battlestar Galactica: The Story So Far        1.99
7      2820                  Occupation / Precipice        1.99
8      2822                           Exodus, Pt. 2        1.99
9      2828                             The Passage        1.99

### Q8 — Find long tracks
##### Business question - Which tracks are longer than 10 minutes?

In [12]:
# Q8 — Tracks longer than 10 minutes

query = """
SELECT
    track_id,
    name AS track_name,
    milliseconds,
    ROUND(milliseconds / 60000.0, 2) AS duration_minutes
FROM track
WHERE milliseconds > 600000
ORDER BY milliseconds DESC;
"""

df = pd.read_sql_query(query, engine)
df

,track_id,track_name,milliseconds,duration_minutes
0,2820,Occupation / Precipice,5286953,88.12
1,3224,Through a Looking Glass,5088838,84.81
2,3244,"Greetings from Earth, Pt. 1",2960293,49.34
3,3242,The Man With Nine Lives,2956998,49.28
4,3227,"Battlestar Galactica, Pt. 2",2956081,49.27
...,...,...,...,...
255,2433,The Way You Do To Mer,618344,10.31
256,548,Smoke On The Water,618031,10.30
257,1442,Revolution 1993,616829,10.28
258,1173,Coma,616511,10.28
259,770,Child In Time (Son Of Aleric - Instrumental),602880,10.05

### Q9 - Find missing company information
##### Business question - Which customers do not have a company recorded?

In [13]:
query = """

SELECT 
    customer_id,
    first_name,
    last_name,
    phone,
    company
FROM customer
WHERE company IS NULL;

"""

df = pd.read_sql_query(query, engine)
df

    customer_id first_name     last_name                phone company
0             2     Leonie        Köhler     +49 0711 2842222    None
1             3   François      Tremblay    +1 (514) 721-4711    None
2             4      Bjørn        Hansen      +47 22 44 22 22    None
3             6     Helena          Holý     +420 2 4177 0449    None
4             7     Astrid        Gruber       +43 01 5134505    None
5             8       Daan       Peeters     +32 02 219 03 03    None
6             9       Kara       Nielsen       +453 3331 9991    None
7            13   Fernanda         Ramos   +55 (61) 3363-5547    None
8            18   Michelle        Brooks    +1 (212) 221-3546    None
9            20        Dan        Miller    +1 (650) 644-3358    None
10           21      Kathy         Chase    +1 (775) 223-7665    None
11           22    Heather       Leacock    +1 (407) 999-7788    None
12           23       John        Gordon    +1 (617) 522-1333    None
13           24      Frank       Ralston    +1 (312) 332-3232    None
14           25     Victor       Stevens    +1 (608) 257-0597    None
15           26    Richard    Cunningham    +1 (817) 924-7272    None
16           27    Patrick          Gray    +1 (520) 622-4200    None
17           28      Julia       Barnett    +1 (801) 531-7272    None
18           29     Robert         Brown    +1 (416) 363-8888    None
19           30     Edward       Francis    +1 (613) 234-3322    None
20           31     Martha          Silk    +1 (902) 450-0450    None
21           32      Aaron      Mitchell    +1 (204) 452-6452    None
22           33      Ellie      Sullivan    +1 (867) 920-2233    None
23           34       João     Fernandes   +351 (213) 466-111    None
24           35   Madalena       Sampaio   +351 (225) 022-448    None
25           36     Hannah     Schneider     +49 030 26550280    None
26           37       Fynn    Zimmermann     +49 069 40598889    None
27           38     Niklas      Schröder      +49 030 2141444    None
28           39    Camille       Bernard   +33 01 49 70 65 65    None
29           40  Dominique      Lefebvre   +33 01 47 42 71 71    None
30           41       Marc        Dubois   +33 04 78 30 30 30    None
31           42      Wyatt        Girard   +33 05 56 96 96 96    None
32           43   Isabelle       Mercier   +33 03 80 73 66 99    None
33           44      Terhi    Hämäläinen     +358 09 870 2000    None
34           45   Ladislav        Kovács                  NaN    None
35           46       Hugh      O'Reilly      +353 01 6792424    None
36           47      Lucas       Mancini      +39 06 39733434    None
37           48   Johannes  Van der Berg      +31 020 6223130    None
38           49  Stanisław        Wójcik     +48 22 828 37 39    None
39           50    Enrique         Muñoz      +34 914 454 454    None
40           51     Joakim     Johansson     +46 08-651 52 52    None
41           52       Emma         Jones    +44 020 7707 0707    None
42           53       Phil        Hughes    +44 020 7976 5722    None
43           54      Steve        Murray    +44 0131 315 3300    None
44           55       Mark        Taylor   +61 (02) 9332 3633    None
45           56      Diego     Gutiérrez  +54 (0)11 4311 4333    None
46           57       Luis         Rojas    +56 (0)2 635 4444    None
47           58      Manoj        Pareek    +91 0124 39883988    None
48           59       Puja    Srivastava     +91 080 22289999    None

### Q10 - Count the customers
##### Business question - How many customers are in the database?

In [14]:
# Q10 — Total number of customers

query = """
SELECT
    COUNT(*) AS total_customers
FROM customer;
"""

df = pd.read_sql_query(query, engine)
df

   total_customers
0               59

### Q11 — Find the minimum and maximum invoice
##### Business question - What are the smallest and largest invoice values?

In [15]:
# Q11 — Minimum and maximum invoice values

query = """
SELECT
    MIN(total) AS minimum_invoice,
    MAX(total) AS maximum_invoice
FROM invoice;
"""

df = pd.read_sql_query(query, engine)
df

   minimum_invoice  maximum_invoice
0             0.99            25.86

### Q12 - Calculate total revenue
##### Business question - What is the total revenue generated by the store?

In [16]:
# Q12 - Total revenue

query = """
SELECT
    ROUND(SUM(total), 2) AS total_revenue
FROM invoice;
"""

df = pd.read_sql_query(query, engine)
df

   total_revenue
0         2328.6

### Q13 - Calculate average invoice value
##### Business question - What is the average value of an invoice?

In [17]:
# Q13 — Average invoice value

query = """
SELECT
    ROUND(AVG(total), 2) AS average_invoice_value
FROM invoice;
"""

df = pd.read_sql_query(query, engine)
df

   average_invoice_value
0                   5.65

### Q14 - Count customers by country
##### Business question - How many customers does the store have in each country?

In [18]:
# Q14 - Customer count by country

query = """
SELECT
    country,
    COUNT(*) AS customer_count
FROM customer
GROUP BY country
ORDER BY customer_count DESC, country;
"""

df = pd.read_sql_query(query, engine)
df

           country  customer_count
0              USA              13
1           Canada               8
2           Brazil               5
3           France               5
4          Germany               4
5   United Kingdom               3
6   Czech Republic               2
7            India               2
8         Portugal               2
9        Argentina               1
10       Australia               1
11         Austria               1
12         Belgium               1
13           Chile               1
14         Denmark               1
15         Finland               1
16         Hungary               1
17         Ireland               1
18           Italy               1
19     Netherlands               1
20          Norway               1
21          Poland               1
22           Spain               1
23          Sweden               1

### Q15 - Calculate sales by country
##### Business question: How much revenue does each billing country generate?

In [19]:
# Q15 — Total sales by billing country

query = """
SELECT
    billing_country AS country,
    ROUND(SUM(total), 2) AS total_sales
FROM invoice
GROUP BY billing_country
ORDER BY total_sales DESC;
"""

df = pd.read_sql_query(query, engine)
df

           country  total_sales
0              USA       523.06
1           Canada       303.96
2           France       195.10
3           Brazil       190.10
4          Germany       156.48
5   United Kingdom       112.86
6   Czech Republic        90.24
7         Portugal        77.24
8            India        75.26
9            Chile        46.62
10         Ireland        45.62
11         Hungary        45.62
12         Austria        42.62
13         Finland        41.62
14     Netherlands        40.62
15          Norway        39.62
16          Sweden        38.62
17       Argentina        37.62
18         Belgium        37.62
19          Poland        37.62
20       Australia        37.62
21           Italy        37.62
22         Denmark        37.62
23           Spain        37.62

### Q16 - Find customers with repeat purchases
##### Business question - Which customers have more than one invoice?

In [20]:
# Q16 - Customers with more than one invoice

query = """
SELECT
    customer_id,
    COUNT(invoice_id) AS invoice_count
FROM invoice
GROUP BY customer_id
HAVING COUNT(invoice_id) > 1
ORDER BY invoice_count DESC, customer_id;
"""

df = pd.read_sql_query(query, engine)
df

    customer_id  invoice_count
0             1              7
1             2              7
2             3              7
3             4              7
4             5              7
5             6              7
6             7              7
7             8              7
8             9              7
9            10              7
10           11              7
11           12              7
12           13              7
13           14              7
14           15              7
15           16              7
16           17              7
17           18              7
18           19              7
19           20              7
20           21              7
21           22              7
22           23              7
23           24              7
24           25              7
25           26              7
26           27              7
27           28              7
28           29              7
29           30              7
30           31              7
31           32              7
32           33              7
33           34              7
34           35              7
35           36              7
36           37              7
37           38              7
38           39              7
39           40              7
40           41              7
41           42              7
42           43              7
43           44              7
44           45              7
45           46              7
46           47              7
47           48              7
48           49              7
49           50              7
50           51              7
51           52              7
52           53              7
53           54              7
54           55              7
55           56              7
56           57              7
57           58              7
58           59              6

### Q17 - Find the top-selling tracks
##### Business question - Which tracks have sold the most units?

In [21]:
# Q17 — Top-selling tracks

query = """
SELECT
    t.track_id,
    t.name AS track_name,
    SUM(il.quantity) AS units_sold,
    ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue
FROM track AS t
INNER JOIN invoice_line AS il
    ON t.track_id = il.track_id
GROUP BY
    t.track_id,
    t.name
ORDER BY
    units_sold DESC,
    revenue DESC
LIMIT 10;
"""

df = pd.read_sql_query(query, engine)
df

   track_id                    track_name  units_sold  revenue
0      3177                      Hot Girl           2     3.98
1      3250                         Pilot           2     3.98
2      3223  How to Stop an Exploding Man           2     3.98
3      3200                Gay Witch Hunt           2     3.98
4      2832                The Woman King           2     3.98
5      2850                       The Fix           2     3.98
6      3214             Phyllis's Wedding           2     3.98
7      2868                     Walkabout           2     3.98
8      2404                 Right On Time           2     1.98
9      2054                      Selvagem           2     1.98

### Q18 - Find the top-selling albums
##### Business question - Which albums have sold the most units?

In [22]:
# Q18 — Top-selling albums

query = """
SELECT
    a.album_id,
    a.title AS album_title,
    SUM(il.quantity) AS units_sold,
    ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue
FROM album AS a
INNER JOIN track AS t
    ON a.album_id = t.album_id
INNER JOIN invoice_line AS il
    ON t.track_id = il.track_id
GROUP BY
    a.album_id,
    a.title
ORDER BY
    units_sold DESC,
    revenue DESC
LIMIT 10;
"""

df = pd.read_sql_query(query, engine)
df

   album_id                               album_title  units_sold  revenue
0        23                            Minha Historia          27    26.73
1       141                             Greatest Hits          26    25.74
2        73                                 Unplugged          25    24.75
3       224                                  Acústico          22    21.78
4        37                             Greatest Kiss          20    19.80
5        21                              Prenda Minha          19    18.81
6       221  My Generation - The Very Best Of The Who          19    18.81
7        55                         Chronicle, Vol. 2          19    18.81
8       253  Battlestar Galactica (Classic), Season 1          18    35.82
9        54                         Chronicle, Vol. 1          18    17.82

### Q19 - Find the highest-spending customers
##### Business question - Which customers have spent the most money?

In [23]:
# Q19 — Highest-spending customers

query = """
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.country,
    ROUND(SUM(i.total), 2) AS total_spent
FROM customer AS c
INNER JOIN invoice AS i
    ON c.customer_id = i.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name,
    c.country
ORDER BY total_spent DESC
LIMIT 10;
"""

df = pd.read_sql_query(query, engine)
df

   customer_id first_name   last_name         country  total_spent
0            6     Helena        Holý  Czech Republic        49.62
1           26    Richard  Cunningham             USA        47.62
2           57       Luis       Rojas           Chile        46.62
3           46       Hugh    O'Reilly         Ireland        45.62
4           45   Ladislav      Kovács         Hungary        45.62
5           28      Julia     Barnett             USA        43.62
6           24      Frank     Ralston             USA        43.62
7           37       Fynn  Zimmermann         Germany        43.62
8           25     Victor     Stevens             USA        42.62
9            7     Astrid      Gruber         Austria        42.62

### Q20 - Find the top-selling genres
##### Business question - Which genres generate the most sales?

In [24]:
# Q20 — Top-selling genres

query = """
SELECT
    g.genre_id,
    g.name AS genre,
    SUM(il.quantity) AS units_sold,
    ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue
FROM genre AS g
INNER JOIN track AS t
    ON g.genre_id = t.genre_id
INNER JOIN invoice_line AS il
    ON t.track_id = il.track_id
GROUP BY
    g.genre_id,
    g.name
ORDER BY
    units_sold DESC,
    revenue DESC;
"""

df = pd.read_sql_query(query, engine)
df

    genre_id               genre  units_sold  revenue
0          1                Rock         835   826.65
1          7               Latin         386   382.14
2          3               Metal         264   261.36
3          4  Alternative & Punk         244   241.56
4          2                Jazz          80    79.20
5          6               Blues          61    60.39
6         19            TV Shows          47    93.53
7         14            R&B/Soul          41    40.59
8         24           Classical          41    40.59
9          8              Reggae          30    29.70
10        21               Drama          29    57.71
11         9                 Pop          28    27.72
12        20    Sci Fi & Fantasy          20    39.80
13        10          Soundtrack          20    19.80
14        17         Hip Hop/Rap          17    16.83
15        11          Bossa Nova          15    14.85
16        23         Alternative          14    13.86
17        16               World          13    12.87
18        13         Heavy Metal          12    11.88
19        15   Electronica/Dance          12    11.88
20        12      Easy Listening          10     9.90
21        22              Comedy           9    17.91
22        18     Science Fiction           6    11.94
23         5       Rock And Roll           6     5.94

### Q21 - Which invoices belong to which customers?
##### Business Question - Which customers have made purchases, and what are their invoice amounts?

In [25]:
# Q21 — Business Question:
# Which customers have made purchases, and what are their invoice amounts?
# Purpose: Connect customers with their individual invoices.

query = """
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    i.invoice_id,
    i.invoice_date,
    i.total
FROM customer AS c
INNER JOIN invoice AS i
    ON c.customer_id = i.customer_id
ORDER BY
    c.customer_id,
    i.invoice_date;
"""

df = pd.read_sql_query(query, engine)
df

     customer_id first_name   last_name  invoice_id invoice_date  total
0              1       Luís   Gonçalves          98   2022-03-11   3.98
1              1       Luís   Gonçalves         121   2022-06-13   3.96
2              1       Luís   Gonçalves         143   2022-09-15   5.94
3              1       Luís   Gonçalves         195   2023-05-06   0.99
4              1       Luís   Gonçalves         316   2024-10-27   1.98
..           ...        ...         ...         ...          ...    ...
407           59       Puja  Srivastava          45   2021-07-08   5.94
408           59       Puja  Srivastava          97   2022-02-26   1.99
409           59       Puja  Srivastava         218   2023-08-20   1.98
410           59       Puja  Srivastava         229   2023-09-30  13.86
411           59       Puja  Srivastava         284   2024-05-30   8.91

[412 rows x 6 columns]

### Q22 - What products did each customer purchase?
##### Business Question - Which tracks were purchased by each customer?

In [26]:
# Q22 — Business Question:
# Which tracks were purchased by each customer?
# Purpose: Connect customers, invoices, and purchased line items.

query = """
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    i.invoice_id,
    il.track_id,
    il.quantity,
    il.unit_price
FROM customer AS c
INNER JOIN invoice AS i
    ON c.customer_id = i.customer_id
INNER JOIN invoice_line AS il
    ON i.invoice_id = il.invoice_id
ORDER BY
    c.customer_id,
    i.invoice_id,
    il.track_id;
"""

df = pd.read_sql_query(query, engine)
df

,customer_id,first_name,last_name,invoice_id,track_id,quantity,unit_price
0,1,Luís,Gonçalves,98,3247,1,1.99
1,1,Luís,Gonçalves,98,3248,1,1.99
2,1,Luís,Gonçalves,121,447,1,0.99
3,1,Luís,Gonçalves,121,449,1,0.99
4,1,Luís,Gonçalves,121,451,1,0.99
...,...,...,...,...,...,...,...
2235,59,Puja,Srivastava,284,2340,1,0.99
2236,59,Puja,Srivastava,284,2346,1,0.99
2237,59,Puja,Srivastava,284,2352,1,0.99
2238,59,Puja,Srivastava,284,2358,1,0.99
2239,59,Puja,Srivastava,284,2364,1,0.99

### Q23 - Which artist and album does each track belong to?
##### Business Question - What artist and album are associated with each track?

In [27]:
# Q23 — Business Question:
# Which artist and album does each track belong to?
# Purpose: Build a complete catalog hierarchy from artist to track.

query = """
SELECT
    t.track_id,
    t.name AS track_name,
    a.title AS album_title,
    ar.name AS artist_name
FROM track AS t
INNER JOIN album AS a
    ON t.album_id = a.album_id
INNER JOIN artist AS ar
    ON a.artist_id = ar.artist_id
ORDER BY
    ar.name,
    a.title,
    t.name;
"""

df = pd.read_sql_query(query, engine)
df

,track_id,track_name,album_title,artist_name
0,3427,Fanfare for the Common Man,"A Copland Celebration, Vol. I",Aaron Copland & London Symphony Orchestra
1,3357,OAM's Blues,Worlds,Aaron Goldberg
2,12,Breaking The Rules,For Those About To Rock We Salute You,AC/DC
3,11,C.O.D.,For Those About To Rock We Salute You,AC/DC
4,10,Evil Walks,For Those About To Rock We Salute You,AC/DC
...,...,...,...,...
3498,3155,Sem Essa de Malandro Agulha,Ao Vivo [IMPORT],Zeca Pagodinho
3499,3151,Seu Balancê,Ao Vivo [IMPORT],Zeca Pagodinho
3500,3152,Vai Adiar,Ao Vivo [IMPORT],Zeca Pagodinho
3501,3164,Verdade,Ao Vivo [IMPORT],Zeca Pagodinho
3502,3149,Vivo Isolado Do Mundo,Ao Vivo [IMPORT],Zeca Pagodinho

### Q24 - Which genres have generated sales?
##### Business Question - How many units and how much revenue has each genre generated?

In [28]:
# Q24 — Business Question:
# How many units and how much revenue has each genre generated?
# Purpose: Measure genre-level sales performance.

query = """
SELECT
    g.genre_id,
    g.name AS genre,
    SUM(il.quantity) AS units_sold,
    ROUND(SUM(il.unit_price * il.quantity), 2) AS revenue
FROM genre AS g
INNER JOIN track AS t
    ON g.genre_id = t.genre_id
INNER JOIN invoice_line AS il
    ON t.track_id = il.track_id
GROUP BY
    g.genre_id,
    g.name
ORDER BY
    revenue DESC;
"""

df = pd.read_sql_query(query, engine)
df

    genre_id               genre  units_sold  revenue
0          1                Rock         835   826.65
1          7               Latin         386   382.14
2          3               Metal         264   261.36
3          4  Alternative & Punk         244   241.56
4         19            TV Shows          47    93.53
5          2                Jazz          80    79.20
6          6               Blues          61    60.39
7         21               Drama          29    57.71
8         14            R&B/Soul          41    40.59
9         24           Classical          41    40.59
10        20    Sci Fi & Fantasy          20    39.80
11         8              Reggae          30    29.70
12         9                 Pop          28    27.72
13        10          Soundtrack          20    19.80
14        22              Comedy           9    17.91
15        17         Hip Hop/Rap          17    16.83
16        11          Bossa Nova          15    14.85
17        23         Alternative          14    13.86
18        16               World          13    12.87
19        18     Science Fiction           6    11.94
20        13         Heavy Metal          12    11.88
21        15   Electronica/Dance          12    11.88
22        12      Easy Listening          10     9.90
23         5       Rock And Roll           6     5.94

### Q25 - What did each customer purchase?
##### Business Question - Which customer purchased which track, from which album, and from which artist?

In [29]:
# Q25 — Business Question:
# Which customer purchased which track, album, and artist?
# Purpose: Create a detailed customer purchase history.

query = """
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    i.invoice_id,
    i.invoice_date,
    t.track_id,
    t.name AS track_name,
    a.title AS album_title,
    ar.name AS artist_name,
    il.quantity,
    il.unit_price,
    ROUND(il.quantity * il.unit_price, 2) AS line_revenue
FROM customer AS c
INNER JOIN invoice AS i
    ON c.customer_id = i.customer_id
INNER JOIN invoice_line AS il
    ON i.invoice_id = il.invoice_id
INNER JOIN track AS t
    ON il.track_id = t.track_id
INNER JOIN album AS a
    ON t.album_id = a.album_id
INNER JOIN artist AS ar
    ON a.artist_id = ar.artist_id
ORDER BY
    c.customer_id,
    i.invoice_date,
    t.name;
"""

df = pd.read_sql_query(query, engine)
df

,customer_id,first_name,last_name,invoice_id,invoice_date,track_id,track_name,album_title,artist_name,quantity,unit_price,line_revenue
0,1,Luís,Gonçalves,98,2022-03-11,3247,Experiment In Terra,"Battlestar Galactica (Classic), Season 1",Battlestar Galactica (Classic),1,1.99,1.99
1,1,Luís,Gonçalves,98,2022-03-11,3248,Take the Celestra,"Battlestar Galactica (Classic), Season 1",Battlestar Galactica (Classic),1,1.99,1.99
2,1,Luís,Gonçalves,121,2022-06-13,449,Calling Dr. Love,Greatest Kiss,Kiss,1,0.99,0.99
3,1,Luís,Gonçalves,121,2022-06-13,453,Cold Gin,Greatest Kiss,Kiss,1,0.99,0.99
4,1,Luís,Gonçalves,121,2022-06-13,447,Shout It Out Loud,Greatest Kiss,Kiss,1,0.99,0.99
...,...,...,...,...,...,...,...,...,...,...,...,...
2235,59,Puja,Srivastava,284,2024-05-30,2346,No Fundo Do Quintal Da Escola,Raul Seixas,Raul Seixas,1,0.99,0.99
2236,59,Puja,Srivastava,284,2024-05-30,2352,Que Luz É Essa,Raul Seixas,Raul Seixas,1,0.99,0.99
2237,59,Puja,Srivastava,284,2024-05-30,2322,So Central Rain,The Best Of R.E.M.: The IRS Years,R.E.M.,1,0.99,0.99
2238,59,Puja,Srivastava,284,2024-05-30,2316,Texarkana,Out Of Time,R.E.M. Feat. Kate Pearson,1,0.99,0.99
2239,59,Puja,Srivastava,284,2024-05-30,2358,The Power Of Equality,Blood Sugar Sex Magik,Red Hot Chili Peppers,1,0.99,0.99

### Q26 - Which artists have no albums?
##### Business Question - Are there artists in the database who do not have any album?

In [30]:
# Q26 — Business Question:
# Which artists do not have any albums in the database?
# Purpose: Identify artists with no associated album records.

query = """
SELECT
    ar.artist_id,
    ar.name AS artist_name
FROM artist AS ar
LEFT JOIN album AS a
    ON ar.artist_id = a.artist_id
WHERE a.album_id IS NULL
ORDER BY ar.name;
"""

df = pd.read_sql_query(query, engine)
df

    artist_id                                        artist_name
0          43                                       A Cor Do Som
1         239  Academy of St. Martin in the Fields, Sir Nevil...
2         161        Aerosmith & Sierra Leone's Refugee Allstars
3         166                                      Avril Lavigne
4          26                                            Azymuth
..        ...                                                ...
66         73                           Vinícius E Qurteto Em Cy
67         75                Vinicius, Toquinho & Quarteto Em Cy
68        154                                         Whitesnake
69        181                                                Xis
70        168                                     Youssou N'Dour

[71 rows x 2 columns]

### Q27 - Which albums have no tracks?
##### Business Question - Are there any albums in the catalog that do not contain tracks?

In [31]:
# Q27 — Business Question:
# Which albums do not have any tracks?
# Purpose: Identify albums with missing track associations.

query = """
SELECT
    a.album_id,
    a.title AS album_title
FROM album AS a
LEFT JOIN track AS t
    ON a.album_id = t.album_id
WHERE t.track_id IS NULL
ORDER BY a.title;
"""

df = pd.read_sql_query(query, engine)
df

Empty DataFrame
Columns: [album_id, album_title]
Index: []

### Q28 - Which employees are assigned to customers?
##### Business Question - Which customers are supported by each employee?

In [32]:
query = """
SELECT
    e.employee_id,
    e.first_name AS employee_first_name,
    e.last_name AS employee_last_name,
    c.customer_id,
    c.first_name AS customer_first_name,
    c.last_name AS customer_last_name
FROM employee AS e
LEFT JOIN customer AS c
    ON e.employee_id = c.support_rep_id
ORDER BY
    e.employee_id,
    c.customer_id;
"""

df = pd.read_sql_query(query, engine)
df

,employee_id,employee_first_name,employee_last_name,customer_id,customer_first_name,customer_last_name
0,1,Andrew,Adams,NaN,NaN,NaN
1,2,Nancy,Edwards,NaN,NaN,NaN
2,3,Jane,Peacock,1.0,Luís,Gonçalves
3,3,Jane,Peacock,3.0,François,Tremblay
4,3,Jane,Peacock,12.0,Roberto,Almeida
...,...,...,...,...,...,...
59,5,Steve,Johnson,54.0,Steve,Murray
60,5,Steve,Johnson,57.0,Luis,Rojas
61,6,Michael,Mitchell,NaN,NaN,NaN
62,7,Robert,King,NaN,NaN,NaN
63,8,Laura,Callahan,NaN,NaN,NaN

### Q29 - Which employees have no customers assigned?
##### Business Question - Which support employees currently have no customers assigned to them?

In [34]:
# Q29 - Business Question:
# Which employees have no customers assigned to them?
# Purpose: Identify support representatives with no current customer assignments.

query = """
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    e.title
FROM employee AS e
LEFT JOIN customer AS c
    ON e.employee_id = c.support_rep_id
WHERE c.customer_id IS NULL
ORDER BY e.employee_id;
"""

df = pd.read_sql_query(query, engine)
df

   employee_id first_name last_name            title
0            1     Andrew     Adams  General Manager
1            2      Nancy   Edwards    Sales Manager
2            6    Michael  Mitchell       IT Manager
3            7     Robert      King         IT Staff
4            8      Laura  Callahan         IT Staff

### Q30 - How much revenue does each employee generate?
##### Business Question: How much revenue is generated by customers assigned to each employee?

In [35]:
query = """
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    e.title,
    COUNT(DISTINCT c.customer_id) AS customers_supported,
    COUNT(DISTINCT i.invoice_id) AS invoices_handled,
    ROUND(COALESCE(SUM(i.total), 0), 2) AS total_revenue
FROM employee AS e
LEFT JOIN customer AS c
    ON e.employee_id = c.support_rep_id
LEFT JOIN invoice AS i
    ON c.customer_id = i.customer_id
GROUP BY
    e.employee_id,
    e.first_name,
    e.last_name,
    e.title
ORDER BY
    total_revenue DESC;
"""

df = pd.read_sql_query(query, engine)
df

,employee_id,first_name,last_name,title,customers_supported,invoices_handled,total_revenue
0,3,Jane,Peacock,Sales Support Agent,21,146,833.04
1,4,Margaret,Park,Sales Support Agent,20,140,775.40
2,5,Steve,Johnson,Sales Support Agent,18,126,720.16
3,7,Robert,King,IT Staff,0,0,0.00
4,1,Andrew,Adams,General Manager,0,0,0.00
5,8,Laura,Callahan,IT Staff,0,0,0.00
6,2,Nancy,Edwards,Sales Manager,0,0,0.00
7,6,Michael,Mitchell,IT Manager,0,0,0.00

### Q31 - What is the employee reporting hierarchy?
##### Business Question: Who does each employee report to?

In [36]:
query = """
SELECT
    e.employee_id,
    e.first_name AS employee_first_name,
    e.last_name AS employee_last_name,
    e.title AS employee_title,
    m.employee_id AS manager_id,
    m.first_name AS manager_first_name,
    m.last_name AS manager_last_name,
    m.title AS manager_title
FROM employee AS e
LEFT JOIN employee AS m
    ON e.reports_to = m.employee_id
ORDER BY
    e.employee_id;
"""

df = pd.read_sql_query(query, engine)
df

,employee_id,employee_first_name,employee_last_name,employee_title,manager_id,manager_first_name,manager_last_name,manager_title
0,1,Andrew,Adams,General Manager,NaN,NaN,NaN,NaN
1,2,Nancy,Edwards,Sales Manager,1.0,Andrew,Adams,General Manager
2,3,Jane,Peacock,Sales Support Agent,2.0,Nancy,Edwards,Sales Manager
3,4,Margaret,Park,Sales Support Agent,2.0,Nancy,Edwards,Sales Manager
4,5,Steve,Johnson,Sales Support Agent,2.0,Nancy,Edwards,Sales Manager
5,6,Michael,Mitchell,IT Manager,1.0,Andrew,Adams,General Manager
6,7,Robert,King,IT Staff,6.0,Michael,Mitchell,IT Manager
7,8,Laura,Callahan,IT Staff,6.0,Michael,Mitchell,IT Manager

### Q32 - RIGHT JOIN: Which employees have customer assignments?
##### Business Question: Which employees are associated with customers, while preserving all employee records from the right side of the join?

In [37]:
query = """
SELECT
    c.customer_id,
    c.first_name AS customer_first_name,
    c.last_name AS customer_last_name,
    e.employee_id,
    e.first_name AS employee_first_name,
    e.last_name AS employee_last_name
FROM customer AS c
RIGHT JOIN employee AS e
    ON c.support_rep_id = e.employee_id
ORDER BY
    e.employee_id,
    c.customer_id;
"""

df = pd.read_sql_query(query, engine)
df

,customer_id,customer_first_name,customer_last_name,employee_id,employee_first_name,employee_last_name
0,NaN,NaN,NaN,1,Andrew,Adams
1,NaN,NaN,NaN,2,Nancy,Edwards
2,1.0,Luís,Gonçalves,3,Jane,Peacock
3,3.0,François,Tremblay,3,Jane,Peacock
4,12.0,Roberto,Almeida,3,Jane,Peacock
...,...,...,...,...,...,...
59,54.0,Steve,Murray,5,Steve,Johnson
60,57.0,Luis,Rojas,5,Steve,Johnson
61,NaN,NaN,NaN,6,Michael,Mitchell
62,NaN,NaN,NaN,7,Robert,King
63,NaN,NaN,NaN,8,Laura,Callahan

### Q33 - FULL OUTER JOIN between artists and albums
##### Business Question: Which artists and albums have relationships, and are there any artists or albums without a matching record?

In [38]:
query = """
SELECT
    ar.artist_id,
    ar.name AS artist_name,
    a.album_id,
    a.title AS album_title
FROM artist AS ar
FULL OUTER JOIN album AS a
    ON ar.artist_id = a.artist_id
ORDER BY
    ar.artist_id,
    a.album_id;
"""

df = pd.read_sql_query(query, engine)
df

,artist_id,artist_name,album_id,album_title
0,1,AC/DC,1.0,For Those About To Rock We Salute You
1,1,AC/DC,4.0,Let There Be Rock
2,2,Accept,2.0,Balls to the Wall
3,2,Accept,3.0,Restless and Wild
4,3,Aerosmith,5.0,Big Ones
...,...,...,...,...
413,271,"Mela Tenenbaum, Pro Musica Prague & Richard Kapp",342.0,"Locatelli: Concertos for Violin, Strings and C..."
414,272,Emerson String Quartet,344.0,Schubert: The Late String Quartets & String Qu...
415,273,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...",345.0,Monteverdi: L'Orfeo
416,274,Nash Ensemble,346.0,Mozart: Chamber Music
417,275,Philip Glass Ensemble,347.0,Koyaanisqatsi (Soundtrack from the Motion Pict...

### Q34 - Complete customer sales report
##### Business Question: What did each customer purchase, when did they purchase it, and how much did the purchase contribute to revenue?

In [39]:
query = """
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.country,
    i.invoice_id,
    i.invoice_date,
    t.track_id,
    t.name AS track_name,
    il.quantity,
    il.unit_price,
    ROUND(il.quantity * il.unit_price, 2) AS line_revenue
FROM customer AS c
INNER JOIN invoice AS i
    ON c.customer_id = i.customer_id
INNER JOIN invoice_line AS il
    ON i.invoice_id = il.invoice_id
INNER JOIN track AS t
    ON il.track_id = t.track_id
ORDER BY
    c.customer_id,
    i.invoice_date,
    t.name;
"""

df = pd.read_sql_query(query, engine)
df

,customer_id,first_name,last_name,country,invoice_id,invoice_date,track_id,track_name,quantity,unit_price,line_revenue
0,1,Luís,Gonçalves,Brazil,98,2022-03-11,3247,Experiment In Terra,1,1.99,1.99
1,1,Luís,Gonçalves,Brazil,98,2022-03-11,3248,Take the Celestra,1,1.99,1.99
2,1,Luís,Gonçalves,Brazil,121,2022-06-13,449,Calling Dr. Love,1,0.99,0.99
3,1,Luís,Gonçalves,Brazil,121,2022-06-13,453,Cold Gin,1,0.99,0.99
4,1,Luís,Gonçalves,Brazil,121,2022-06-13,447,Shout It Out Loud,1,0.99,0.99
...,...,...,...,...,...,...,...,...,...,...,...
2235,59,Puja,Srivastava,India,284,2024-05-30,2346,No Fundo Do Quintal Da Escola,1,0.99,0.99
2236,59,Puja,Srivastava,India,284,2024-05-30,2352,Que Luz É Essa,1,0.99,0.99
2237,59,Puja,Srivastava,India,284,2024-05-30,2322,So Central Rain,1,0.99,0.99
2238,59,Puja,Srivastava,India,284,2024-05-30,2316,Texarkana,1,0.99,0.99
2239,59,Puja,Srivastava,India,284,2024-05-30,2358,The Power Of Equality,1,0.99,0.99

### Q35 - Detailed track sales by artist and album
##### Business Question: Which artists and albums generate the most track-level sales revenue?

In [40]:
query = """
SELECT
    ar.artist_id,
    ar.name AS artist_name,
    a.album_id,
    a.title AS album_title,
    t.track_id,
    t.name AS track_name,
    SUM(il.quantity) AS units_sold,
    ROUND(SUM(il.quantity * il.unit_price), 2) AS revenue
FROM artist AS ar
INNER JOIN album AS a
    ON ar.artist_id = a.artist_id
INNER JOIN track AS t
    ON a.album_id = t.album_id
INNER JOIN invoice_line AS il
    ON t.track_id = il.track_id
GROUP BY
    ar.artist_id,
    ar.name,
    a.album_id,
    a.title,
    t.track_id,
    t.name
ORDER BY
    revenue DESC,
    units_sold DESC
LIMIT 100;
"""

df = pd.read_sql_query(query, engine)
df

,artist_id,artist_name,album_id,album_title,track_id,track_name,units_sold,revenue
0,148,Heroes,228,"Heroes, Season 1",2850,The Fix,2,3.98
1,159,Aquaman,254,Aquaman,3250,Pilot,2,3.98
2,147,Battlestar Galactica,227,"Battlestar Galactica, Season 3",2832,The Woman King,2,3.98
3,156,The Office,251,"The Office, Season 3",3214,Phyllis's Wedding,2,3.98
4,156,The Office,249,"The Office, Season 1",3177,Hot Girl,2,3.98
...,...,...,...,...,...,...,...,...
95,149,Lost,230,"Lost, Season 1",2877,The Moth,1,1.99
96,158,Battlestar Galactica (Classic),253,"Battlestar Galactica (Classic), Season 1",3229,"Lost Planet of the Gods, Pt. 1",1,1.99
97,149,Lost,230,"Lost, Season 1",2923,Exodus (Part 2) [Season Finale],1,1.99
98,147,Battlestar Galactica,227,"Battlestar Galactica, Season 3",2823,Collaborators,1,1.99
99,158,Battlestar Galactica (Classic),253,"Battlestar Galactica (Classic), Season 1",3238,"The Living Legend, Pt. 2",1,1.99

### Q36 - Monthly Sales Report
##### Business Question: How much revenue is generated each month, and how many invoices are created each month?

In [41]:
q36 = """
SELECT
    DATE_TRUNC('month', invoice_date) AS sales_month,
    COUNT(invoice_id) AS total_invoices,
    ROUND(SUM(total), 2) AS total_revenue,
    ROUND(AVG(total), 2) AS average_invoice_value
FROM invoice
GROUP BY
    DATE_TRUNC('month', invoice_date)
ORDER BY
    sales_month;
"""

df_q36 = pd.read_sql_query(q36, engine)

df_q36

   sales_month  total_invoices  total_revenue  average_invoice_value
0   2021-01-01               6          35.64                   5.94
1   2021-02-01               7          37.62                   5.37
2   2021-03-01               7          37.62                   5.37
3   2021-04-01               7          37.62                   5.37
4   2021-05-01               7          37.62                   5.37
5   2021-06-01               7          37.62                   5.37
6   2021-07-01               7          37.62                   5.37
7   2021-08-01               7          37.62                   5.37
8   2021-09-01               7          37.62                   5.37
9   2021-10-01               7          37.62                   5.37
10  2021-11-01               7          37.62                   5.37
11  2021-12-01               7          37.62                   5.37
12  2022-01-01               7          52.62                   7.52
13  2022-02-01               7          46.62                   6.66
14  2022-03-01               7          44.62                   6.37
15  2022-04-01               7          37.62                   5.37
16  2022-05-01               7          37.62                   5.37
17  2022-06-01               7          37.62                   5.37
18  2022-07-01               7          37.62                   5.37
19  2022-08-01               7          37.62                   5.37
20  2022-09-01               6          36.63                   6.11
21  2022-10-01               7          37.62                   5.37
22  2022-11-01               7          37.62                   5.37
23  2022-12-01               7          37.62                   5.37
24  2023-01-01               7          37.62                   5.37
25  2023-02-01               7          37.62                   5.37
26  2023-03-01               7          37.62                   5.37
27  2023-04-01               7          51.62                   7.37
28  2023-05-01               7          42.62                   6.09
29  2023-06-01               7          50.62                   7.23
30  2023-07-01               7          37.62                   5.37
31  2023-08-01               7          37.62                   5.37
32  2023-09-01               7          37.62                   5.37
33  2023-10-01               7          37.62                   5.37
34  2023-11-01               6          23.76                   3.96
35  2023-12-01               7          37.62                   5.37
36  2024-01-01               7          37.62                   5.37
37  2024-02-01               7          37.62                   5.37
38  2024-03-01               7          37.62                   5.37
39  2024-04-01               7          37.62                   5.37
40  2024-05-01               7          37.62                   5.37
41  2024-06-01               7          37.62                   5.37
42  2024-07-01               7          39.62                   5.66
43  2024-08-01               7          47.62                   6.80
44  2024-09-01               6          46.71                   7.79
45  2024-10-01               7          42.62                   6.09
46  2024-11-01               7          37.62                   5.37
47  2024-12-01               7          37.62                   5.37
48  2025-01-01               7          37.62                   5.37
49  2025-02-01               5          27.72                   5.54
50  2025-03-01               7          37.62                   5.37
51  2025-04-01               5          33.66                   6.73
52  2025-05-01               7          37.62                   5.37
53  2025-06-01               7          37.62                   5.37
54  2025-07-01               7          37.62                   5.37
55  2025-08-01               7          37.62                   5.37
56  2025-09-01               7          37.62                   5.37
57  2025-10-01               7          37.62                   5.37
58  2025-11-01               7          49.62                   7.09
59  2025-12-01               7          38.62                   5.52

### Q37 - Yearly Sales Analysis
##### Business Question: How much revenue did the business generate in each year?

In [42]:
q37 = """
SELECT
    EXTRACT(YEAR FROM invoice_date) AS sales_year,
    COUNT(invoice_id) AS total_invoices,
    ROUND(SUM(total), 2) AS total_revenue,
    ROUND(AVG(total), 2) AS average_invoice_value
FROM invoice
GROUP BY
    EXTRACT(YEAR FROM invoice_date)
ORDER BY
    sales_year;
"""

df_q37 = pd.read_sql_query(q37, engine)

df_q37

   sales_year  total_invoices  total_revenue  average_invoice_value
0      2021.0              83         449.46                   5.42
1      2022.0              83         481.45                   5.80
2      2023.0              83         469.58                   5.66
3      2024.0              83         477.53                   5.75
4      2025.0              80         450.58                   5.63

### Q38 - Countries Exceeding a Revenue Threshold
##### Business Question: Which countries generated more than $50 in total revenue?

In [43]:
q38 = """
SELECT
    billing_country,
    COUNT(invoice_id) AS total_invoices,
    ROUND(SUM(total), 2) AS total_revenue
FROM invoice
GROUP BY
    billing_country
HAVING
    SUM(total) > 50
ORDER BY
    total_revenue DESC;
"""

df_q38 = pd.read_sql_query(q38, engine)

df_q38

  billing_country  total_invoices  total_revenue
0             USA              91         523.06
1          Canada              56         303.96
2          France              35         195.10
3          Brazil              35         190.10
4         Germany              28         156.48
5  United Kingdom              21         112.86
6  Czech Republic              14          90.24
7        Portugal              14          77.24
8           India              13          75.26

### Q39 - Invoices Above Average Invoice Value
##### Business Question: Which invoices have a value greater than the average invoice value across all invoices?

In [44]:
q39 = """
SELECT
    invoice_id,
    customer_id,
    invoice_date,
    billing_country,
    ROUND(total, 2) AS invoice_total
FROM invoice
WHERE total > (
    SELECT AVG(total)
    FROM invoice
)
ORDER BY
    total DESC;
"""

df_q39 = pd.read_sql_query(q39, engine)

df_q39

     invoice_id  customer_id invoice_date billing_country  invoice_total
0           404            6   2025-11-13  Czech Republic          25.86
1           299           26   2024-08-05             USA          23.86
2           194           46   2023-04-28         Ireland          21.86
3            96           45   2022-02-18         Hungary          21.86
4            89            7   2022-01-18         Austria          18.86
..          ...          ...          ...             ...            ...
174         276           15   2024-04-26          Canada           5.94
175         164           56   2022-12-17       Argentina           5.94
176         374           16   2025-07-04             USA           5.94
177         283           53   2024-05-27  United Kingdom           5.94
178         402           50   2025-11-05           Spain           5.94

[179 rows x 5 columns]

### Q40 - Customers Spending Above Average
##### Business Question: Which customers have spent more than the average amount spent by customers?

In [45]:
q40 = """
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    ROUND(SUM(i.total), 2) AS total_spent
FROM customer c
JOIN invoice i
    ON c.customer_id = i.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
HAVING
    SUM(i.total) > (
        SELECT AVG(customer_total)
        FROM (
            SELECT
                customer_id,
                SUM(total) AS customer_total
            FROM invoice
            GROUP BY customer_id
        ) AS customer_spending
    )
ORDER BY
    total_spent DESC;
"""

df_q40 = pd.read_sql_query(q40, engine)

df_q40

    customer_id first_name     last_name  total_spent
0             6     Helena          Holý        49.62
1            26    Richard    Cunningham        47.62
2            57       Luis         Rojas        46.62
3            45   Ladislav        Kovács        45.62
4            46       Hugh      O'Reilly        45.62
5            24      Frank       Ralston        43.62
6            37       Fynn    Zimmermann        43.62
7            28      Julia       Barnett        43.62
8            25     Victor       Stevens        42.62
9             7     Astrid        Gruber        42.62
10           44      Terhi    Hämäläinen        41.62
11            5  František   Wichterlová        40.62
12           43   Isabelle       Mercier        40.62
13           48   Johannes  Van der Berg        40.62
14           42      Wyatt        Girard        39.62
15            3   François      Tremblay        39.62
16           17       Jack         Smith        39.62
17           20        Dan        Miller        39.62
18           22    Heather       Leacock        39.62
19           34       João     Fernandes        39.62
20            1       Luís     Gonçalves        39.62
21            4      Bjørn        Hansen        39.62

### Q41 - Rank Tracks by Sales Within Each Genre
##### Business Question: Which tracks are the best-selling tracks within each genre?

In [46]:
q41 = """
WITH track_sales AS (
    SELECT
        g.genre_id,
        g.name AS genre_name,
        t.track_id,
        t.name AS track_name,
        SUM(il.quantity) AS units_sold,
        ROUND(SUM(il.quantity * il.unit_price), 2) AS revenue
    FROM genre g
    JOIN track t
        ON g.genre_id = t.genre_id
    JOIN invoice_line il
        ON t.track_id = il.track_id
    GROUP BY
        g.genre_id,
        g.name,
        t.track_id,
        t.name
)

SELECT
    genre_name,
    track_id,
    track_name,
    units_sold,
    revenue,
    RANK() OVER (
        PARTITION BY genre_id
        ORDER BY units_sold DESC
    ) AS sales_rank
FROM track_sales
ORDER BY
    genre_name,
    sales_rank;
"""

df_q41 = pd.read_sql_query(q41, engine)

df_q41

,genre_name,track_id,track_name,units_sold,revenue,sales_rank
0,Alternative,3401,Show Me How to Live (Live at the Quart Festival),1,0.99,1
1,Alternative,3378,Safe and Sound,1,0.99,1
2,Alternative,3365,Say Hello 2 Heaven,1,0.99,1
3,Alternative,3369,Call Me a Dog,1,0.99,1
4,Alternative,3400,Moth,1,0.99,1
...,...,...,...,...,...,...
1979,World,1964,Já Foi,1,0.99,1
1980,World,1536,Voce Inteira,1,0.99,1
1981,World,1963,É Fogo,1,0.99,1
1982,World,1967,A Moça e a Chuva,1,0.99,1
1983,World,1539,Equinocio,1,0.99,1

### Q42 - Running Total of Revenue
##### Business Question: How does total revenue accumulate month by month?

In [47]:
q42 = """
WITH monthly_sales AS (
    SELECT
        DATE_TRUNC('month', invoice_date) AS sales_month,
        ROUND(SUM(total), 2) AS monthly_revenue
    FROM invoice
    GROUP BY
        DATE_TRUNC('month', invoice_date)
)

SELECT
    sales_month,
    monthly_revenue,
    ROUND(
        SUM(monthly_revenue) OVER (
            ORDER BY sales_month
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ),
        2
    ) AS running_revenue
FROM monthly_sales
ORDER BY
    sales_month;
"""

df_q42 = pd.read_sql_query(q42, engine)

df_q42

   sales_month  monthly_revenue  running_revenue
0   2021-01-01            35.64            35.64
1   2021-02-01            37.62            73.26
2   2021-03-01            37.62           110.88
3   2021-04-01            37.62           148.50
4   2021-05-01            37.62           186.12
5   2021-06-01            37.62           223.74
6   2021-07-01            37.62           261.36
7   2021-08-01            37.62           298.98
8   2021-09-01            37.62           336.60
9   2021-10-01            37.62           374.22
10  2021-11-01            37.62           411.84
11  2021-12-01            37.62           449.46
12  2022-01-01            52.62           502.08
13  2022-02-01            46.62           548.70
14  2022-03-01            44.62           593.32
15  2022-04-01            37.62           630.94
16  2022-05-01            37.62           668.56
17  2022-06-01            37.62           706.18
18  2022-07-01            37.62           743.80
19  2022-08-01            37.62           781.42
20  2022-09-01            36.63           818.05
21  2022-10-01            37.62           855.67
22  2022-11-01            37.62           893.29
23  2022-12-01            37.62           930.91
24  2023-01-01            37.62           968.53
25  2023-02-01            37.62          1006.15
26  2023-03-01            37.62          1043.77
27  2023-04-01            51.62          1095.39
28  2023-05-01            42.62          1138.01
29  2023-06-01            50.62          1188.63
30  2023-07-01            37.62          1226.25
31  2023-08-01            37.62          1263.87
32  2023-09-01            37.62          1301.49
33  2023-10-01            37.62          1339.11
34  2023-11-01            23.76          1362.87
35  2023-12-01            37.62          1400.49
36  2024-01-01            37.62          1438.11
37  2024-02-01            37.62          1475.73
38  2024-03-01            37.62          1513.35
39  2024-04-01            37.62          1550.97
40  2024-05-01            37.62          1588.59
41  2024-06-01            37.62          1626.21
42  2024-07-01            39.62          1665.83
43  2024-08-01            47.62          1713.45
44  2024-09-01            46.71          1760.16
45  2024-10-01            42.62          1802.78
46  2024-11-01            37.62          1840.40
47  2024-12-01            37.62          1878.02
48  2025-01-01            37.62          1915.64
49  2025-02-01            27.72          1943.36
50  2025-03-01            37.62          1980.98
51  2025-04-01            33.66          2014.64
52  2025-05-01            37.62          2052.26
53  2025-06-01            37.62          2089.88
54  2025-07-01            37.62          2127.50
55  2025-08-01            37.62          2165.12
56  2025-09-01            37.62          2202.74
57  2025-10-01            37.62          2240.36
58  2025-11-01            49.62          2289.98
59  2025-12-01            38.62          2328.60

### Q43 - Three-Month Moving Average
##### Business Question: What is the average monthly revenue over the current month and the previous two months?

In [48]:
q43 = """
WITH monthly_sales AS (
    SELECT
        DATE_TRUNC('month', invoice_date) AS sales_month,
        ROUND(SUM(total), 2) AS monthly_revenue
    FROM invoice
    GROUP BY
        DATE_TRUNC('month', invoice_date)
)

SELECT
    sales_month,
    monthly_revenue,
    ROUND(
        AVG(monthly_revenue) OVER (
            ORDER BY sales_month
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ),
        2
    ) AS three_month_moving_average
FROM monthly_sales
ORDER BY
    sales_month;
"""

df_q43 = pd.read_sql_query(q43, engine)

df_q43

   sales_month  monthly_revenue  three_month_moving_average
0   2021-01-01            35.64                       35.64
1   2021-02-01            37.62                       36.63
2   2021-03-01            37.62                       36.96
3   2021-04-01            37.62                       37.62
4   2021-05-01            37.62                       37.62
5   2021-06-01            37.62                       37.62
6   2021-07-01            37.62                       37.62
7   2021-08-01            37.62                       37.62
8   2021-09-01            37.62                       37.62
9   2021-10-01            37.62                       37.62
10  2021-11-01            37.62                       37.62
11  2021-12-01            37.62                       37.62
12  2022-01-01            52.62                       42.62
13  2022-02-01            46.62                       45.62
14  2022-03-01            44.62                       47.95
15  2022-04-01            37.62                       42.95
16  2022-05-01            37.62                       39.95
17  2022-06-01            37.62                       37.62
18  2022-07-01            37.62                       37.62
19  2022-08-01            37.62                       37.62
20  2022-09-01            36.63                       37.29
21  2022-10-01            37.62                       37.29
22  2022-11-01            37.62                       37.29
23  2022-12-01            37.62                       37.62
24  2023-01-01            37.62                       37.62
25  2023-02-01            37.62                       37.62
26  2023-03-01            37.62                       37.62
27  2023-04-01            51.62                       42.29
28  2023-05-01            42.62                       43.95
29  2023-06-01            50.62                       48.29
30  2023-07-01            37.62                       43.62
31  2023-08-01            37.62                       41.95
32  2023-09-01            37.62                       37.62
33  2023-10-01            37.62                       37.62
34  2023-11-01            23.76                       33.00
35  2023-12-01            37.62                       33.00
36  2024-01-01            37.62                       33.00
37  2024-02-01            37.62                       37.62
38  2024-03-01            37.62                       37.62
39  2024-04-01            37.62                       37.62
40  2024-05-01            37.62                       37.62
41  2024-06-01            37.62                       37.62
42  2024-07-01            39.62                       38.29
43  2024-08-01            47.62                       41.62
44  2024-09-01            46.71                       44.65
45  2024-10-01            42.62                       45.65
46  2024-11-01            37.62                       42.32
47  2024-12-01            37.62                       39.29
48  2025-01-01            37.62                       37.62
49  2025-02-01            27.72                       34.32
50  2025-03-01            37.62                       34.32
51  2025-04-01            33.66                       33.00
52  2025-05-01            37.62                       36.30
53  2025-06-01            37.62                       36.30
54  2025-07-01            37.62                       37.62
55  2025-08-01            37.62                       37.62
56  2025-09-01            37.62                       37.62
57  2025-10-01            37.62                       37.62
58  2025-11-01            49.62                       41.62
59  2025-12-01            38.62                       41.95

### Q44 - Top 3 Tracks in Each Genre
##### Business Question: What are the top 3 best-selling tracks in each genre?

In [49]:
q44 = """
WITH track_sales AS (
    SELECT
        g.genre_id,
        g.name AS genre_name,
        t.track_id,
        t.name AS track_name,
        SUM(il.quantity) AS units_sold,
        ROUND(SUM(il.quantity * il.unit_price), 2) AS revenue
    FROM genre g
    JOIN track t
        ON g.genre_id = t.genre_id
    JOIN invoice_line il
        ON t.track_id = il.track_id
    GROUP BY
        g.genre_id,
        g.name,
        t.track_id,
        t.name
),

ranked_tracks AS (
    SELECT
        genre_name,
        track_id,
        track_name,
        units_sold,
        revenue,
        ROW_NUMBER() OVER (
            PARTITION BY genre_id
            ORDER BY units_sold DESC, track_id
        ) AS track_rank
    FROM track_sales
)

SELECT
    genre_name,
    track_id,
    track_name,
    units_sold,
    revenue,
    track_rank
FROM ranked_tracks
WHERE track_rank <= 3
ORDER BY
    genre_name,
    track_rank;
"""

df_q44 = pd.read_sql_query(q44, engine)

df_q44

,genre_name,track_id,track_name,units_sold,revenue,track_rank
0,Alternative,3365,Say Hello 2 Heaven,1,0.99,1
1,Alternative,3369,Call Me a Dog,1,0.99,2
2,Alternative,3373,Four Walled World,1,0.99,3
3,Alternative & Punk,171,Bowels Of The Devil,2,1.98,1
4,Alternative & Punk,175,Voodoo,2,1.98,2
...,...,...,...,...,...,...
67,TV Shows,3177,Hot Girl,2,3.98,2
68,TV Shows,3200,Gay Witch Hunt,2,3.98,3
69,World,1535,No Futuro,1,0.99,1
70,World,1536,Voce Inteira,1,0.99,2
71,World,1539,Equinocio,1,0.99,3

### Q45 - Comprehensive Business Intelligence Dashboard
##### Business Question: What are the main sales and customer performance metrics for the Chinook store?

In [50]:
q45 = """
WITH sales_summary AS (
    SELECT
        COUNT(DISTINCT i.invoice_id) AS total_invoices,
        COUNT(DISTINCT i.customer_id) AS active_customers,
        ROUND(SUM(i.total), 2) AS total_revenue,
        ROUND(AVG(i.total), 2) AS average_invoice_value
    FROM invoice i
),

track_summary AS (
    SELECT
        SUM(il.quantity) AS total_units_sold,
        COUNT(DISTINCT il.track_id) AS different_tracks_sold
    FROM invoice_line il
),

top_track AS (
    SELECT
        t.name AS top_track_name,
        SUM(il.quantity) AS units_sold
    FROM track t
    JOIN invoice_line il
        ON t.track_id = il.track_id
    GROUP BY
        t.track_id,
        t.name
    ORDER BY
        units_sold DESC
    LIMIT 1
),

top_genre AS (
    SELECT
        g.name AS top_genre_name,
        SUM(il.quantity) AS units_sold
    FROM genre g
    JOIN track t
        ON g.genre_id = t.genre_id
    JOIN invoice_line il
        ON t.track_id = il.track_id
    GROUP BY
        g.genre_id,
        g.name
    ORDER BY
        units_sold DESC
    LIMIT 1
)

SELECT
    s.total_invoices,
    s.active_customers,
    s.total_revenue,
    s.average_invoice_value,
    ts.total_units_sold,
    ts.different_tracks_sold,
    tt.top_track_name,
    tt.units_sold AS top_track_units_sold,
    tg.top_genre_name,
    tg.units_sold AS top_genre_units_sold
FROM sales_summary s
CROSS JOIN track_summary ts
CROSS JOIN top_track tt
CROSS JOIN top_genre tg;
"""

df_q45 = pd.read_sql_query(q45, engine)

df_q45

,total_invoices,active_customers,total_revenue,average_invoice_value,total_units_sold,different_tracks_sold,top_track_name,top_track_units_sold,top_genre_name,top_genre_units_sold
0,412,59,2328.6,5.65,2240,1984,Motorbreath,2,Rock,835